version: "3"
services:
  mongo:
    image: mongo:3.4-jessie
    command: mongod --port 47017
    volumes:
      - ".volumes/mongo:/data/db:Z"
  consul:
    image: consul
    environment:
     - "CONSUL_BIND_INTERFACE=eth0"
    links:
      - mongo
    ports:
      - 8500:8500
  app:
    build: ./api-seed
    image: rso-seed
    environment:
      - NODE_ENV=prod
      - MONGO_HOST=mongodb://mongo:47017/frirso
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
      - CONSUL_HOST=${CONSUL_HOST}
    ports:
      - 6001:3000
    links:
      - auth
    depends_on:
      - mongo
      - consul
  auth:
      build: ./rso-auth
      image: rso-auth
      environment:
        - NODE_ENV=prod
        - MONGO_HOST=mongodb://mongo:47017/frirso
        - LOGZIO_TOKEN=${LOGZIO_TOKEN}
        - CONSUL_HOST=${CONSUL_HOST}
      ports:
        - 6002:3000
      depends_on:
        - mongo
        - consul
